### ISSUE TITLE
Throws "ValueError: substring not found"

### ISSUE THREAD

**Issue by chris9797** [thesunRider/Amber#2]
```
Traceback (most recent call last):
  File "amber.py", line 272, in <module>
    main_interface(sys.argv[1:])
  File "amber.py", line 82, in main_interface
    start_process()
  File "amber.py", line 166, in start_process
    data2 = data2[data2.index('android:name="')+len('android:name="'):data2.index('"/>')]
ValueError: substring not found

```

**Comment by thesunRider** [comment]
DM me the Application you used to bind to
